/**********************************************************************************************************************
*  FILE DESCRIPTION
*  -----------------------------------------------------------------------------------------------------------------*/
/**        \file  Port_PBcfg.c
*        \descriptoin  Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
*
*      \Author: Salah Mahmoud 
*		
*
*********************************************************************************************************************/

/* Defining the Module software verison by Major.Minor.Patch format */
/* Module 1.0.0 */

#define PORT_PBCFG_SW_MAJOR_VERSION				(1U)
#define PORT_PBCFG_SW_MINOR_VERSION				(0U)
#define PORT_PBCFG_SW_PATCH_VERSION				(0U)

/* Defining the autosar version ued for the module */
/* Autosar version 4.0.3 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION		(4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION		(0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION		(3U)


/* Checking for software version compitability */
/* Checking for autosar veriosn compitability */
/**********************************************************************************************************************
*  INCLUDES
*********************************************************************************************************************/
#include "Port.h"

/* checking autosar and software version compatability between port.h and port_cfg.h */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
||   (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
||   (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
#error "The software version of Port.h is not matching this module version"
#endif

#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
||	 (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
  ||	 (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The autosar version of Port.h is not matching this module version"
#endif

/**********************************************************************************************************************
*  GLOBAL DATA
*********************************************************************************************************************/

/*define your configuration files in the below order */
/*PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,
PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE */

/*{portPinNumber,portPortNumber, portPinMode,portPinDirection,portInitialValueIfOutput,portOutputCurrent
,portPinResistorAttchIfInput,PortPinDirectionChangeable,PortPinModeChangeable}*/

Port_ConfigType Port_Configuration =
{
  
  {{PORT_PIN_A_0,PORT_PORT_A,PORT_DEFAULT_PIN_MODE,PORT_PIN_IN,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_A_1,PORT_PORT_A,PORT_PA1_DIO,PORT_PIN_OUT,STD_LOW,PORT_OCURRENT_2_MA, PORT_NA, TRUE, FALSE},
  {PORT_PIN_A_2,PORT_PORT_A,PORT_PA2_DIO,PORT_PIN_OUT,STD_LOW,PORT_OCURRENT_2_MA, PORT_NA, FALSE, FALSE},
  {PORT_PIN_A_3,PORT_PORT_A,PORT_PA3_DIO,PORT_PIN_OUT,STD_LOW,PORT_OCURRENT_2_MA, PORT_NA, FALSE, FALSE},
  {PORT_PIN_A_4,PORT_PORT_A,PORT_PA4_DIO,PORT_PIN_OUT,STD_LOW,PORT_OCURRENT_2_MA, PORT_NA, FALSE, FALSE},
  {PORT_PIN_A_5,PORT_PORT_A,PORT_PA5_DIO,PORT_PIN_OUT,STD_LOW,PORT_OCURRENT_2_MA, PORT_NA, FALSE, FALSE},
  {PORT_PIN_A_6,PORT_PORT_A,PORT_PA6_DIO,PORT_PIN_OUT,STD_LOW,PORT_OCURRENT_2_MA, PORT_NA, FALSE, FALSE},
  {PORT_PIN_A_7,PORT_PORT_A,PORT_PA7_DIO,PORT_PIN_OUT,STD_LOW,PORT_OCURRENT_2_MA, PORT_NA, FALSE, FALSE},
  {PORT_PIN_B_0,PORT_PORT_B,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_B_1,PORT_PORT_B,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_B_2,PORT_PORT_B,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_B_3,PORT_PORT_B,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_B_4,PORT_PORT_B,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_B_5,PORT_PORT_B,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_B_6,PORT_PORT_B,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_B_7,PORT_PORT_B,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_C_4,PORT_PORT_C,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_C_5,PORT_PORT_C,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_C_6,PORT_PORT_C,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_C_7,PORT_PORT_C,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_D_0,PORT_PORT_D,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_D_1,PORT_PORT_D,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_D_2,PORT_PORT_D,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_D_3,PORT_PORT_D,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_D_4,PORT_PORT_D,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_D_5,PORT_PORT_D,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_D_6,PORT_PORT_D,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_D_7,PORT_PORT_D,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_E_0,PORT_PORT_E,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_E_1,PORT_PORT_E,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_E_2,PORT_PORT_E,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_E_3,PORT_PORT_E,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_E_4,PORT_PORT_E,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_E_5,PORT_PORT_E,PORT_DEFAULT_PIN_MODE,PORT_DEFAULT_PIN_DIRECTION,PORT_DEFAULT_LEVEL,PORT_DEFAULT_OUTPUT_CURRENT,PORT_DEFAULT_RESISTOR_TYPE,PORT_DEFAULT_IS_DIRECTION_CHANGEABLE,PORT_DEFAULT_IS_PIN_MODE_CHANGEABLE}, 
  {PORT_PIN_F_0,PORT_PORT_F,PORT_PF0_DIO,PORT_PIN_IN, STD_LOW,PORT_OCURRENT_2_MA, PORT_ATTACH_PULL_UP_RESISTOR, FALSE, FALSE},
  {PORT_PIN_F_1,PORT_PORT_F,PORT_PF1_DIO,PORT_PIN_OUT, STD_LOW,PORT_OCURRENT_2_MA, PORT_ATTACH_PULL_UP_RESISTOR, FALSE, FALSE},
  {PORT_PIN_F_2,PORT_PORT_F,PORT_PF2_DIO,PORT_PIN_OUT, STD_LOW,PORT_OCURRENT_2_MA, PORT_ATTACH_PULL_UP_RESISTOR, FALSE, FALSE},
  {PORT_PIN_F_3,PORT_PORT_F,PORT_PF3_DIO,PORT_PIN_OUT, STD_LOW,PORT_OCURRENT_2_MA, PORT_ATTACH_PULL_UP_RESISTOR, FALSE, FALSE},
  {PORT_PIN_F_4,PORT_PORT_F,PORT_PF4_DIO,PORT_PIN_IN, STD_LOW,PORT_OCURRENT_2_MA, PORT_ATTACH_PULL_UP_RESISTOR, FALSE, TRUE}}
  

};



/**********************************************************************************************************************
*  END OF FILE: Port_PBCfg.c
*********************************************************************************************************************/
